### ISSUE TITLE
create routes

### ISSUE THREAD

**Issue by syboulette** [syboulette/fridgi#4]

**Comment by Za-hell** [comment]
- [ ] Need to redo the line 14. It conflicts with line 7 (Joao opinion) Sheets User Stories
- [ ] Line 19 and 13 conflict. Sheets User Stories
- [ ] Joao suggest a dashboard for favorite recipes in /pages_controller/dashboard/def_dash
- [ ] Line 26. Sheets User Stories -should we change the action to destroy ?
- [ ] The paths should always be plural.
- [ ] Line 8 is done by devise.
